### ISSUE TITLE
network optimizations

### ISSUE THREAD

**Issue by TheMaskedMan00** [Sacchan-VRC/MS-VRCSA-Billiards#5]
looking through the code I notice that nobody really uses shorts or bytes instead of ints

a player id can never be greater than 83 (unless its some vrchat mega instance which in that case use a short instead) so its acceptable to use a byte or sbyte (-128 - 127) to represent a player ID, as it also takes up less network space.

using bytes as bools is acceptable since they have the same network size

All sizes are listed here: https://doc.photonengine.com/realtime/current/reference/serialization-in-photon

An integer is an extra 2 bytes compared to a short, and nobody needs values up to 2 billion, and if you do, what are you doing?
shorts can carry values from -32,000 to 32,000 roughly. an extra 2 bytes might not seem like much, but when you have alot of objects constantly sending out data it can go a long way. 

some things i found that could easily be switched:

`syncedCueSkin` (int) in CueController.cs can be switched to a byte or if you are crazy and need more than 256 skins, a short.

`playerIDsSynced` (int[4]) in NetworkingManager.cs can be switched to a sbyte[4], since there will (almost) never be more than 128 players in any given instance, and using an sbyte rather than a normal byte means you are sacrificing half of the capacity in the positive numbers and making room for negative numbers. or just use a short[4] if you are worried about the vrchat mega instances.

`stateIdSynced` (int) in NetworkingManager.cs can be switched to a short, Maybe it can be a byte, although I haven't dug through all of the code yet so I'm not sure if a byte will be able to store what it needs.

`ballsPocketedSynced` (uint) in NetworkingManager.cs can be switched to a ushort, Now I'm no expert in pool, but i don't think we can ever possibly pocket 4 billion balls.

that's just a few examples of things I have already changed, But since its such a simple fix, I don't see the need for me to comb through all the code and figure out how it works just to switch a few types. You guys already know how it all works so I'll let you make the necessary changes.

Remember, Every byte counts!

**Comment by TheMaskedMan00** [comment]
also please dont use default vrchat object sync, its terrible. I recommend MMaleons smart object sync or lightsync

**Comment by Sacchan-VRC** [comment]
- a player id can never be greater than 83 / playerIDsSynced 
 
Player ID is incremented for each player that joins, never re-using a number, pretty sure it can go very high, I prefer to use the same type VRChat returns for this, possible to use ushort, probably. Could maybe cause problems with extremely longstanding instances / if vrchat implements instances that don't close if everyone leaves
 - syncedCueSkin (int) in CueController.cs
 
isn't even used in hte default prefab, i should probably unsync it and let anyone who wants to add sync back in their fork
 - stateIdSynced
 
yeah this can probably be a ushort, I doubt a game is gonna last 65536 turns
 - ballsPocketedSynced
 
it's a bitmask, but the game with the most balls is 8ball with 16, so it can be a ushort, pretty sure I didn't change it because I'd have to change it back to implement 15red snooker, but I guess that's being left to forks now so I'll do it.

Remember it uses manual sync, and data isn't sent very often.

as for replace vrchat object sync, nah. Using someone else's prefab as a dependancy sucks. VRChat may also improve it in future.

**Comment by TheMaskedMan00** [comment]
"Player ID is incremented for each player that joins, never re-using a number, pretty sure it can go very high, I prefer to use the same type VRChat returns for this, possible to use ushort, probably. Could maybe cause problems with extremely longstanding instances / if vrchat implements instances that don't close if everyone leaves"

I actually never knew this, I just verified this is in fact the case, at least on a small scale with a world that has a max of 4 players. I always assumed the player id would be clamped to the max instance size + 2 and then roll back to the first unused ID. thank you for bringing that to my attention. I now have to change all my code lol, I've been using sbytes to hold player IDs for a while.
